# wrangler.toml

name = "interstellar-nolan"  # Name of your worker
type = "javascript"  # Type of worker

# This is the entry point for your Worker script
main = "worker.js"  # Pointing to the worker.js file

compatibility_date = "2025-04-17"  # Set this to today's date

# Optionally, you can configure routes and custom settings
[build]
  command = "npm install"

# Optionally add this if you're using secret variables or other settings
[[env]]
  name = "production"
  route = "yourdomain.com/*"  # Add the domain you want to route requests to
  zone_id = "your-zone-id"
